### ISSUE TITLE
Code??

### ISSUE THREAD

**Issue by ppengzeng** [jssprz/visual_syntactic_embedding_video_captioning#1]
I am very interested in this paper. When will the code be published?

**Comment by jssprz** [comment]
Sorry, I will be updating the repo this week.

**Comment by czy-orange** [comment]
> Sorry, I will be updating the repo this week.

Great work with excellent performance on two datasets. Looking forward to your code release.

**Comment by jssprz** [comment]
Thank you very much for your interest in our work. I just uploaded the model implementation and evaluation script.
